In [11]:

import pandas as pd

#Data management libraries
import sqlite3

connection = sqlite3.connect("database.sqlite")
df = pd.read_sql_query("SELECT * from whole_data", connection)
connection.close()

In [12]:
df.head(1000)

,level_0,index,lang,location,mention_Arthaud,mention_Asselineau,mention_Cheminade,mention_Dupont-Aignan,mention_Fillon,mention_Hamon,...,mention_Poutou,quoted/retweeted full_text,quoted/retweeted user,quoted/retweeted?,text,timestampms,user,day,hour,score
0,0,0,fr,France,0,0,0,0,1,0,...,0,None,None,1,RT @CamilleFlahaut: Incroyable qu'on taille Fi...,1489839749105,gewöhnungsbedürftig,2017-03-18,12,0.6
1,1,1,fr,"Rueil-Malmaison, Ile-de-France",0,0,0,0,0,0,...,0,None,None,1,RT @CPoilbout: .@AllianceC vote à une très lar...,1489839749160,Yannis de M.,2017-03-18,12,0.2517
2,2,2,fr,"Angers, Maine-et-Loire, France",0,0,0,0,0,1,...,0,Pays récupéré en faillite et au bord de la réc...,Ted2 LeRetour EnPire,1,RT @TedLunique: Pays récupéré en faillite et a...,1489839749315,Crissara #GoFH2017,2017-03-18,12,0.21
3,3,3,fr,"57400 Sarrebourg, France",0,0,0,0,0,0,...,0,None,None,1,RT @OBettati: Ce pauvre #Estrosi est vraiment ...,1489839749277,BUHLER Alfred,2017-03-18,12,0.0217
4,4,4,fr,None,0,0,0,0,0,0,...,0,None,None,0,@MLP_officiel @France3tv Incroyable le nombre ...,1489839749711,Diego de Lyon,2017-03-18,12,0.0633
5,5,5,fr,"Valenciennes, France",0,0,0,0,0,0,...,0,None,None,1,RT @th2re: @pmcouteaux Connait personne qui vo...,1489839750886,SLABO,2017-03-18,12,0.27
6,6,6,fr,None,0,0,0,0,0,0,...,0,None,None,1,RT @Inafr_officiel: 1986 - 2017 : l'ascension ...,1489839751459,Borga,2017-03-18,12,0.0
7,7,7,fr,None,0,0,0,0,0,0,...,0,None,None,1,RT @J2molay: Il est interdit à tout candidat o...,1489839751865,Manuela Richiardi,2017-03-18,12,0.1171
8,8,8,fr,None,0,0,0,0,0,0,...,0,None,None,1,"RT @jeremo12: Hier, #Macron expliquait qu'il f...",1489839752384,koolestleo ▽,2017-03-18,12,0.0
9,9,9,fr,Gard,0,0,0,0,0,1,...,0,None,None,0,@MVAlekseiev pas de chance un electeur de moin...,1489839752998,Dddf30,2017-03-18,12,0.0
10,10,10,fr,France,0,0,0,0,0,0,...,0,None,None,1,RT @pierrebrt: Ou quand même les politiques ut...,1489839753881,Samizo Kouhei,2017-03-18,12,-0.0725
11,12,12,fr,France,0,0,0,0,0,0,...,0,None,None,0,"Emmanuel Macron veut instaurer un ""service nat...",1489839754660,Paris Match,2017-03-18,12,0.085
12,13,13,fr,None,0,0,0,0,0,0,...,0,Oui il serait temps que les français se réveil...,CEMOI CHRIS,1,ILS ONT VOULU LES ARABES ET ILS LES VEULENT EN...,1489839754740,l'oranaise,2017-03-18,12,0.0
13,14,14,fr,"Saint-Mandé, France",0,0,0,0,1,0,...,0,None,None,1,"RT @HeddeMarguerite: ""Emmanuel Macron c'est le...",1489839755188,Hashtags & Emojees,2017-03-18,12,0.0
14,15,15,fr,Près de Lutèce,0,0,0,0,0,0,...,0,None,None,1,RT @Daarjeeling: Un prêt payé à 24h de sa révé...,1489839755517,Ed_,2017-03-18,12,0.2617
15,16,16,fr,Essonne France,0,0,0,0,0,0,...,0,None,None,0,@Nau_Kofi @RassGauchEc @LineduSud @Lenine13 @R...,1489839755708,φ.melody φ,2017-03-18,12,0.175
16,18,18,fr,None,0,0,0,0,1,0,...,0,Les costards de Fillon + importants que les mi...,Maddy2,1,RT @AMaddy2: Les costards de Fillon + importan...,1489839756240,1515LeRetour,2017-03-18,12,0.3
17,19,19,fr,"Pyrénées-Orientales, Languedoc",0,0,0,0,0,0,...,0,None,None,1,RT @GWGoldnadel: Choisie par le CSA sur un cri...,1489839756189,Asperrou Interval🍇,2017-03-18,12,0.0633
18,20,20,fr,None,0,0,0,0,1,0,...,0,None,None,0,"Franchement le ""Fuck François Fillon"" au conce...",1489839756474,valenté,2017-03-18,12,0.0
19,21,21,fr,None,0,0,0,0,0,0,...,0,None,None,0,@LucienLancien @JLMelenchon ça dépend de la fo...,1489839757076,john jones,2017-03-18,12,0.1
20,22,22,fr,"Valenciennes, France",0,0,0,0,1,0,...,0,None,None,1,RT @BONT26932396: @pmcouteaux @Jodubal \nJe su...,1489839757387,SLABO,2017-03-18,12,0.7
21,23,23,fr,None,0,0,0,0,0,0,...,0,Bras droit de #Macron ex délégué interministér...,Francoiszero2,1,RT @beestoufly: Donc chez ##Macron on trouve :...,1489839757866,Txika,2017-03-18,12,0.04
22,24,24,fr,France,0,0,0,0,0,0,...,0,None,None,0,@EmmanuelMacron . C'est ce qu'on appelle une m...,1489839757917,Oggy10,2017-03-18,12,0.1875
23,25,25,fr,None,0,0,0,0,0,0,...,0,None,None,1,RT @BrunoRetailleau: E. Macron propose un serv...,1489839758195,Jabru,2017-03-18,12,-0.09
24,26,26,fr,None,0,0,0,0,0,0,...,0,🗓 Je vous donne rendez-vous à #Metz ce samedi...,Marine Le Pen,1,RT @MLP_officiel: 🗓 Je vous donne rendez-vous...,1489839758274,黎明迷,2017-03-18,12,0.075
25,27,27,fr,MARSEILLE,0,0,0,0,0,0,...,0,None,None,0,Nous sommes prêts @jlm_2017 @jlmelenchon https...,1489839758423,SARAH SOILIHI,2017-03-18,12,0.14
26,28,28,fr,None,0,0,0,0,1,0,...,0,None,None,0,J aimerais...je veux...non j EXIGE le retour d...,1489839758994,Moi ☆,2017-03-18,12,0.2
27,29,29,fr,Montpellier,0,0,0,0,0,0,...,0,None,None,0,@LucienLancien @JLMelenchon On vous récupère a...,1489839759466,Montpellier_squats,2017-03-18,12,0.25
28,30,30,fr,MEOUNES LES MONTRIEUX VAR,0,1,0,0,0,0,...,0,None,None,1,RT @DavoustFranois: Aucun candidat n'explique ...,1489839759465,GRIMAUD GENEVIEVE,2017-03-18,12,0.0
29,31,31,fr,"Montpellier, France",0,0,0,0,0,0,...,0,None,None,1,RT @JmSapet: Mais toutes les générations sont ...,1489839759635,Ker Dan φ,2017-03-18,12,0.0567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,1076,1076,fr,None,0,0,0,0,0,0,...,0,None,None,1,RT @alyciasnkh: allez une petite canicule et o...,1489839978313,IVY PARK,2017-03-18,12,0.125
971,1077,1077,fr,France,0,0,0,0,0,0,...,0,None,None,1,RT @barbare314: @MLP_officiel la france debord...,1489839979080,Muriel M ‏ت,2017-03-18,12,0.0
972,1078,1078,fr,None,0,0,0,0,0,0,...,0,"En 24H: Ramzi égorge ses proches, 1Homme évisc...",GنCøhen🇫🇷🗽🇮🇱,1,RT @Jackeraser2: En 24H: Ramzi égorge ses proc...,1489839979603,Nation... #SPF,2017-03-18,12,0.32
973,1080,1080,fr,None,0,0,0,0,0,0,...,0,None,None,1,"merci Monsieur pour ce décryptage #macron ""soc...",1489839979629,thoron,2017-03-18,12,0.075
974,1081,1081,fr,Paris-Montréal,0,0,0,0,0,1,...,0,None,None,1,RT @phil75011: @LCP Hamon ne représente que le...,1489839980101,Sandra K. MORIN,2017-03-18,12,0.075
975,1082,1082,fr,"57400 Sarrebourg, France",0,0,0,0,0,0,...,0,None,None,1,RT @voinconmc: Présente à Metz au meeting de M...,1489839980452,BUHLER Alfred,2017-03-18,12,0.06
976,1083,1083,fr,"Ain, Rhône-Alpes",0,0,0,0,0,0,...,0,None,None,1,RT @MathieuBourlier: #EnMarche pour la victoir...,1489839980530,Pénélope Chalon,2017-03-18,12,0.0
977,1084,1084,fr,Pornic - Paris,0,0,0,0,0,0,...,0,None,None,0,Avec @EmmanuelMacron c'est la fin des classes ...,1489839980831,Bastien Régnier,2017-03-18,12,-0.0719
978,1085,1085,fr,"Paris, France",0,0,0,0,0,0,...,0,None,None,0,@ErwanBui @MLP_officiel Déjà en rétablissant l...,1489839981249,Jerryster,2017-03-18,12,-0.7
979,1086,1086,fr,Sans patrie Ni frontières,1,0,0,0,0,0,...,0,None,None,1,RT @pzoluca_: pour avoir regardé et Mélenchon ...,1489839981571,olac,2017-03-18,12,-0.04
980,1088,1088,fr,Fransyrie,0,0,0,0,1,0,...,0,None,None,1,RT @rouloubac: Quelques gaullistes devraient e...,1489839982181,KITT,2017-03-18,12,0.0
981,1089,1089,fr,None,0,0,0,0,0,1,...,0,None,None,0,@NicoV83 @Atheepratiquant @AGMarquet\nC'est si...,1489839982685,★Batman & Robin☆,2017-03-18,12,-0.8
982,1090,1090,fr,Vannes Bretagne Sud,0,0,0,0,0,0,...,0,None,None,1,RT @enmarche_2017: [ENQUETE #CEVIPOF]\nCertes...,1489839982832,Alban Moyaux,2017-03-18,12,-0.37
983,1091,1091,fr,FRANCE,0,0,0,0,1,0,...,0,None,None,1,RT @hugoengel4: C'est bon Fillon se positionne...,1489839982823,PATTY69 #marine2017,2017-03-18,12,0.245
984,1092,1092,fr,None,0,0,0,0,0,0,...,0,None,None,1,"RT @LCI: .@FerryLuc : ""Je ne sais pas comment ...",1489839982913,Edmond Dantes ن,2017-03-18,12,0.0
985,1093,1093,fr,"Rennes, France",0,0,0,0,0,0,...,0,🔴📆 @EmmanuelMacron sera l'invité de @Laurent...,Realpolitic,1,RT @Realpolitic_: 🔴📆 @EmmanuelMacron sera l'...,1489839982997,Lucas,2017-03-18,12,0.0
986,1094,1094,fr,"Geneva, Switzerland",0,0,0,0,0,0,...,0,None,None,0,Assurance-vie: Macron précise ses intentions #...,1489839983311,Dukascopy News (FR),2017-03-18,12,0.4
987,1096,1096,fr,"Dubaï, Emirats Arabes Unis",0,0,0,0,0,0,...,0,None,None,0,@MLP_officiel Laxisme? veut dire que les socia...,1489839983517,Samy,2017-03-18,12,0.0
988,1097,1097,fr,Paris,0,0,0,0,0,0,...,0,"Tiens? Un robinet d'eau tiède de plus. ""Ce qu'...",Thomas Montagne,1,RT @binbin59300: Comment le sage @bayrou pourf...,1489839983843,Magda Cavalle,2017-03-18,12,0.1
989,1098,1098,fr,"French Riviera, Nice",0,0,0,0,0,0,...,0,None,None,0,Assez favorable à la proposition d'@EmmanuelMa...,1489839984023,Fʀᴇɴᴄʜ🇫🇷Oɴ Zᴇ Lᴇғᴛ,2017-03-18,12,0.5
990,1099,1099,fr,None,0,0,0,0,0,0,...,0,None,None,1,RT @Atheepratiquant: .@batman3robin j'ai voté ...,1489839984520,Fraternité,2017-03-18,12,0.0
991,1100,1100,fr,France - Neuilly sur seine,0,0,0,0,0,0,...,0,None,None,1,"RT @jeremo12: Hier, #Macron expliquait qu'il f...",1489839984600,Mimoso Beatrice,2017-03-18,12,0.0
992,1101,1101,fr,Seine-Saint-Denis,0,0,0,0,0,0,...,0,None,None,1,Quand je lis certains commentaires c'est tout ...,1489839985114,En marche avec E.M,2017-03-18,12,0.255
993,1102,1102,fr,None,0,0,0,0,0,0,...,0,None,None,0,@AbdelLakhal1 @fhollande @MLP_officiel entrete...,1489839985627,♦♣ C. Claire ♠♥,2017-03-18,12,0.25
994,1103,1103,fr,"Arras, France",0,0,0,0,0,0,...,0,None,None,0,Diffusion du programme d'@EmmanuelMacron à #Cr...,1489839985602,En Marche Arras,2017-03-18,12,0.1
995,1104,1104,fr,None,0,0,0,0,1,0,...,0,None,None,0,"Affaire Fillon. Marc Joulaud convoqué ""en vue ...",1489839985619,Henri Camus,2017-03-18,12,0.0
996,1105,1105,fr,None,0,0,0,0,0,0,...,0,None,None,1,"RT @Gilles_Lebreton: .@Nigel_Farage, le champi...",1489839985856,Patrick kaliciak,2017-03-18,12,0.0
997,1106,1106,fr,"Pure, France",0,0,0,0,0,0,...,0,None,None,0,melenchon est super fort aussi mais j'arrive p...,1489839986272,consider the coconut,2017-03-18,12,0.4033
998,1107,1107,fr,"Languedoc-Roussillon, France",0,0,0,0,0,0,...,0,None,None,1,RT @MarineElysee: Et peu de chances d'être au ...,1489839986562,MANLER,2017-03-18,12,-0.02
999,1108,1108,fr,None,0,0,0,0,1,0,...,0,None,None,1,RT @Papiillon: Le tireur de Grasse s'est donc ...,1489839986592,Alex Bay,2017-03-18,12,-0.275

In [48]:
df1 = df.loc[df['mention_Macron']== 1,['day','score','mention_Macron']]
df1_1 = df1.loc[df1['day'] <'2017-04-24',['day','score','mention_Macron']]

In [49]:
df1_1

                day    score  mention_Macron
1        2017-03-18   0.2517               1
3        2017-03-18   0.0217               1
5        2017-03-18     0.27               1
8        2017-03-18      0.0               1
11       2017-03-18    0.085               1
12       2017-03-18      0.0               1
13       2017-03-18      0.0               1
16       2017-03-18      0.3               1
21       2017-03-18     0.04               1
22       2017-03-18   0.1875               1
23       2017-03-18    -0.09               1
30       2017-03-18  -0.1167               1
31       2017-03-18     -0.5               1
32       2017-03-18      0.0               1
33       2017-03-18  -0.1667               1
34       2017-03-18     0.21               1
38       2017-03-18      0.0               1
39       2017-03-18      0.0               1
41       2017-03-18   0.0525               1
44       2017-03-18      0.0               1
51       2017-03-18      0.0               1
54       2017-03-18   -0.145               1
57       2017-03-18      0.0               1
58       2017-03-18  -0.0712               1
59       2017-03-18      0.5               1
60       2017-03-18      0.0               1
62       2017-03-18      0.5               1
64       2017-03-18   -0.125               1
65       2017-03-18      0.0               1
66       2017-03-18      0.0               1
...             ...      ...             ...
7819622  2017-04-09      0.0               1
7819623  2017-04-09      0.0               1
7819633  2017-04-09      0.0               1
7819665  2017-04-09      0.0               1
7819674  2017-04-09      0.0               1
7819676  2017-04-09      0.0               1
7819724  2017-04-09      0.0               1
7819778  2017-04-09      0.0               1
7819796  2017-04-09     -0.3               1
7819813  2017-04-09      0.0               1
7819835  2017-04-09      0.0               1
7819862  2017-04-09      0.0               1
7819865  2017-04-09      0.0               1
7819873  2017-04-09      0.0               1
7819917  2017-04-09      0.0               1
7819918  2017-04-09      0.0               1
7819930  2017-04-09      0.0               1
7819939  2017-04-09      0.0               1
7819940  2017-04-09      0.0               1
7819963  2017-04-09      0.0               1
7819965  2017-04-09      0.0               1
7820059  2017-04-09      0.0               1
7820095  2017-04-09      0.0               1
7820118  2017-04-09      0.0               1
7820128  2017-04-09      0.0               1
7820132  2017-04-09   0.0625               1
7820139  2017-04-09      0.0               1
7820199  2017-04-09      0.0               1
7820234  2017-04-09      0.0               1
7820246  2017-04-09      0.0               1

[2312136 rows x 3 columns]

In [40]:

df_positive = df1_1.loc[df1_1['score'] > '0.0']

df_positive.count()

day      860032
score    860032
dtype: int64

In [42]:
df_day = df_positive.groupby('day')

In [43]:
[x for x in df_day]

[(u'2017-03-18',                day   score
  1       2017-03-18  0.2517
  3       2017-03-18  0.0217
  5       2017-03-18    0.27
  11      2017-03-18   0.085
  16      2017-03-18     0.3
  21      2017-03-18    0.04
  22      2017-03-18  0.1875
  34      2017-03-18    0.21
  41      2017-03-18  0.0525
  59      2017-03-18     0.5
  62      2017-03-18     0.5
  72      2017-03-18   0.225
  90      2017-03-18  0.1475
  92      2017-03-18   0.085
  97      2017-03-18   0.085
  110     2017-03-18     0.1
  135     2017-03-18   0.185
  136     2017-03-18   0.225
  138     2017-03-18     0.1
  139     2017-03-18     0.2
  140     2017-03-18     0.6
  142     2017-03-18   0.175
  150     2017-03-18   0.065
  163     2017-03-18  0.0675
  165     2017-03-18  0.0175
  168     2017-03-18    0.09
  177     2017-03-18  0.0218
  181     2017-03-18    0.52
  186     2017-03-18  0.3158
  195     2017-03-18  0.0667
  ...            ...     ...
  54327   2017-03-18     0.1
  54333   2017-03-18  0.1325
  54338   2017-03-18    0.22
  54340   2017-03-18    0.75
  170214  2017-03-18     0.5
  170218  2017-03-18    0.55
  170425  2017-03-18  0.1333
  170682  2017-03-18   0.015
  170966  2017-03-18     0.7
  170986  2017-03-18     0.3
  171001  2017-03-18     0.3
  171002  2017-03-18     0.3
  171196  2017-03-18     0.4
  171297  2017-03-18  0.1433
  171565  2017-03-18     0.4
  171846  2017-03-18    0.85
  171904  2017-03-18     0.3
  171915  2017-03-18    0.45
  171963  2017-03-18     0.1
  171991  2017-03-18     0.1
  172019  2017-03-18     0.1
  172059  2017-03-18     0.1
  172096  2017-03-18     0.1
  172273  2017-03-18     0.1
  172482  2017-03-18    0.85
  172554  2017-03-18     0.1
  172578  2017-03-18    0.03
  172591  2017-03-18     0.1
  175362  2017-03-18    0.27
  175630  2017-03-18  0.2188

  [7539 rows x 2 columns]), (u'2017-03-19',                day   score
  54342   2017-03-19     0.2
  54346   2017-03-19  0.0025
  54350   2017-03-19     0.2
  54355   2017-03-19    0.24
  54359   2017-03-19    0.01
  54361   2017-03-19    0.75
  54370   2017-03-19     0.2
  54374   2017-03-19    0.01
  54380   2017-03-19     0.1
  54384   2017-03-19    0.05
  54390   2017-03-19  0.1325
  54391   2017-03-19   0.221
  54393   2017-03-19  0.0933
  54397   2017-03-19    0.18
  54401   2017-03-19  0.1275
  54405   2017-03-19  0.1375
  54409   2017-03-19     0.2
  54410   2017-03-19    0.15
  54413   2017-03-19   0.185
  54415   2017-03-19    0.05
  54417   2017-03-19    0.05
  54419   2017-03-19  0.1375
  54420   2017-03-19     0.2
  54423   2017-03-19  0.0933
  54430   2017-03-19    0.05
  54431   2017-03-19    0.22
  54434   2017-03-19     0.3
  54438   2017-03-19   0.025
  54439   2017-03-19    0.05
  54440   2017-03-19  0.1325
  ...            ...     ...
  183691  2017-03-19     0.3
  183695  2017-03-19     0.5
  183734  2017-03-19  0.4688
  183767  2017-03-19     0.3
  183907  2017-03-19    0.27
  184609  2017-03-19   0.135
  184615  2017-03-19     0.5
  184688  2017-03-19     0.5
  184736  2017-03-19    0.27
  185011  2017-03-19     0.1
  185113  2017-03-19     0.4
  185148  2017-03-19   0.005
  185204  2017-03-19   0.005
  185282  2017-03-19   0.005
  185347  2017-03-19  0.0438
  185678  2017-03-19   0.005
  185725  2017-03-19     0.3
  185732  2017-03-19     0.3
  185748  2017-03-19     0.4
  185986  2017-03-19   0.005
  186558  2017-03-19   0.025
  186722  2017-03-19     0.4
  186723  2017-03-19     0.4
  186885  2017-03-19  0.4688
  186898  2017-03-19  0.0667
  187028  2017-03-19    0.55
  187125  2017-03-19    0.55
  187197  2017-03-19   0.005
  187277  2017-03-19     0.4
  187284  2017-03-19  0.3125

  [19930 rows x 2 columns]), (u'2017-03-20',                 day   score
  187451   2017-03-20    0.03
  187458   2017-03-20   0.175
  187461   2017-03-20   0.125
  187472   2017-03-20  0.2375
  187524   2017-03-20    0.05
  187540   2017-03-20   0.145
  187543   2017-03-20  0.0033
  187545   2017-03-20    0.32
  187548   2017-03-20     0.1
  187563   2017-03-20    0.05
  187571   2017-03-20  0.1583
  187589   2017-03-20   0.035
  187591   2017-03-20     0.5
  187605   2017-03-20    0.11
  187610   2017-03-20    0.25
  187631   2017-03-20  0.0011
  187632   2017-03-20   0.285
  187635   2017-03-20     0.1
  187639   2017-03-20  0.5313
  187649   2017-03-20    0.28
  187651   2017-03-20    0.35
  187653   2017-03-20   0.125
  187656   2017-03-20  0.0667
  187663   2017-03-20  0.1375
  187664   2017-03-20   0.125
  187667   2017-03-20    0.48
  187668   2017-03-20     0.2
  187672   2017-03-20  0.1175
  187673   2017-03-20     0.5
  187711   2017-03-20    0.08
  ...             ...     ...
  1100933  2017-03-20     0.2
  1101094  2017-03-20    0.05
  1101162  2017-03-20     0.1
  1101370  2017-03-20    0.08
  1101422  2017-03-20   0.425
  1101955  2017-03-20     0.5
  1102101  2017-03-20    0.15
  1102296  2017-03-20  0.3375
  1102551  2017-03-20     0.2
  1102585  2017-03-20     0.1
  1102940  2017-03-20     0.7
  1102957  2017-03-20     0.6
  1103097  2017-03-20    0.05
  1103135  2017-03-20   0.425
  1103239  2017-03-20    0.35
  1103289  2017-03-20    0.27
  1103457  2017-03-20  0.1833
  1103592  2017-03-20  0.1417
  1103636  2017-03-20  0.1417
  1103641  2017-03-20  0.0667
  1103657  2017-03-20  0.1417
  1103836  2017-03-20    0.22
  1103930  2017-03-20    0.25
  1104437  2017-03-20    0.22
  1104636  2017-03-20    0.27
  1104767  2017-03-20    0.05
  1104887  2017-03-20    0.05
  1104910  2017-03-20    0.05
  1104964  2017-03-20  0.1417
  1104966  2017-03-20     0.2

  [37430 rows x 2 columns]), (u'2017-03-21',                 day   score
  476774   2017-03-21    0.25
  476775   2017-03-21  0.0975
  476777   2017-03-21  0.0417
  476788   2017-03-21    0.22
  476797   2017-03-21     0.1
  476802   2017-03-21     0.5
  476809   2017-03-21  0.0638
  476810   2017-03-21     0.1
  476833   2017-03-21     0.1
  476843   2017-03-21     0.1
  476844   2017-03-21   0.365
  476847   2017-03-21    0.22
  476853   2017-03-21    0.05
  476857   2017-03-21     0.2
  476869   2017-03-21    0.53
  476873   2017-03-21    0.11
  476880   2017-03-21     0.2
  476882   2017-03-21  0.1187
  476891   2017-03-21    0.25
  476893   2017-03-21  0.0375
  476901   2017-03-21     0.5
  476913   2017-03-21    0.08
  476915   2017-03-21    0.16
  476926   2017-03-21    0.25
  476927   2017-03-21  0.3125
  476929   2017-03-21  0.1883
  476930   2017-03-21  0.0604
  476941   2017-03-21    0.15
  476942   2017-03-21   0.085
  476946   2017-03-21  0.0875
  ...             ...     ...
  1118966  2017-03-21     0.2
  1119048  2017-03-21    0.35
  1119102  2017-03-21     0.7
  1119149  2017-03-21   0.225
  1119155  2017-03-21     0.7
  1119160  2017-03-21     0.4
  1119254  2017-03-21    0.82
  1119319  2017-03-21    0.35
  1119331  2017-03-21     0.7
  1119484  2017-03-21  0.2333
  1119485  2017-03-21     0.4
  1119716  2017-03-21     0.4
  1119752  2017-03-21     0.7
  1119774  2017-03-21    0.05
  1119777  2017-03-21    0.25
  1120709  2017-03-21     0.5
  1120740  2017-03-21     0.5
  1121441  2017-03-21    0.03
  1121525  2017-03-21   0.125
  1121723  2017-03-21     0.7
  1121726  2017-03-21    0.25
  1121853  2017-03-21     0.7
  1121875  2017-03-21     0.7
  1121984  2017-03-21    0.25
  1122008  2017-03-21     0.1
  1122010  2017-03-21     0.7
  1122078  2017-03-21     0.4
  1122096  2017-03-21     0.7
  1122246  2017-03-21     0.5
  1122263  2017-03-21   0.145

  [44786 rows x 2 columns]), (u'2017-03-22',                 day   score
  762079   2017-03-22     0.4
  762083   2017-03-22     0.2
  762084   2017-03-22  0.2625
  762085   2017-03-22    0.17
  762102   2017-03-22   0.025
  762123   2017-03-22  0.0833
  762129   2017-03-22    0.27
  762136   2017-03-22    0.05
  762142   2017-03-22    0.75
  762144   2017-03-22   0.205
  762150   2017-03-22  0.0733
  762169   2017-03-22  0.0733
  762192   2017-03-22     0.2
  762203   2017-03-22  0.3333
  762206   2017-03-22   0.165
  762212   2017-03-22     0.1
  762233   2017-03-22    0.05
  762234   2017-03-22  0.2333
  762235   2017-03-22     0.2
  762246   2017-03-22   0.265
  762278   2017-03-22     0.2
  762290   2017-03-22    0.16
  762294   2017-03-22    0.25
  762297   2017-03-22    0.25
  762298   2017-03-22    0.17
  762300   2017-03-22     0.2
  762315   2017-03-22     0.2
  762317   2017-03-22    0.15
  762318   2017-03-22     0.7
  762320   2017-03-22    0.16
  ...             ...     ...
  1126865  2017-03-22    0.25
  1127013  2017-03-22     0.4
  1127014  2017-03-22    0.25
  1127323  2017-03-22    0.25
  1127350  2017-03-22    0.25
  1127352  2017-03-22  0.0375
  1127837  2017-03-22    0.25
  1127889  2017-03-22     0.7
  1127949  2017-03-22  0.2562
  1128234  2017-03-22    0.25
  1128421  2017-03-22    0.27
  1128543  2017-03-22    0.05
  1128672  2017-03-22  0.1875
  1128709  2017-03-22     1.0
  1128755  2017-03-22    0.25
  1128774  2017-03-22  0.0333
  1128912  2017-03-22    0.27
  1128944  2017-03-22  0.1875
  1129011  2017-03-22  0.0333
  1129139  2017-03-22     0.5
  1129202  2017-03-22   0.205
  1129290  2017-03-22    0.25
  1129294  2017-03-22  0.1875
  1129355  2017-03-22    0.25
  1129429  2017-03-22    0.25
  1129515  2017-03-22     0.1
  1129809  2017-03-22     0.4
  1129923  2017-03-22  0.0675
  1130050  2017-03-22    0.25
  1130125  2017-03-22    0.25

  [20307 rows x 2 columns]), (u'2017-03-23',                 day   score
  913697   2017-03-23   0.175
  913699   2017-03-23  0.1313
  913702   2017-03-23    0.15
  913713   2017-03-23  0.4281
  913715   2017-03-23     0.1
  913718   2017-03-23   0.225
  913723   2017-03-23    0.35
  913724   2017-03-23    0.22
  913730   2017-03-23     0.5
  913731   2017-03-23   0.025
  913738   2017-03-23    0.75
  913745   2017-03-23    0.04
  913746   2017-03-23  0.1875
  913749   2017-03-23   0.205
  913764   2017-03-23  0.0025
  913767   2017-03-23    0.21
  913777   2017-03-23    0.04
  913801   2017-03-23    0.05
  913813   2017-03-23   0.205
  913822   2017-03-23    0.05
  913836   2017-03-23   0.005
  913840   2017-03-23   0.205
  913845   2017-03-23    0.11
  913847   2017-03-23  0.0625
  913856   2017-03-23    0.32
  913857   2017-03-23  0.1225
  913860   2017-03-23    0.22
  913875   2017-03-23    0.32
  913879   2017-03-23  0.2275
  913884   2017-03-23    0.04
  ...             ...     ...
  1137295  2017-03-23     0.1
  1137632  2017-03-23   0.175
  1137797  2017-03-23     0.3
  1138178  2017-03-23    0.25
  1138297  2017-03-23    0.25
  1138379  2017-03-23    0.25
  1138467  2017-03-23    0.25
  1138499  2017-03-23    0.25
  1138714  2017-03-23    0.25
  1138740  2017-03-23    0.25
  1138751  2017-03-23    0.25
  1138764  2017-03-23    0.25
  1138809  2017-03-23  0.0333
  1138821  2017-03-23    0.25
  1139060  2017-03-23    0.25
  1139064  2017-03-23     0.5
  1139106  2017-03-23    0.25
  1139110  2017-03-23  0.0333
  1139113  2017-03-23    0.25
  1139131  2017-03-23  0.0333
  1139161  2017-03-23    0.25
  1139177  2017-03-23  0.0333
  1139324  2017-03-23     0.8
  1139456  2017-03-23  0.1667
  1139627  2017-03-23    0.25
  1139631  2017-03-23    0.25
  1140053  2017-03-23    0.02
  1140107  2017-03-23    0.25
  1140353  2017-03-23     0.1
  1140560  2017-03-23    0.25

  [21182 rows x 2 columns]), (u'2017-03-24',                 day   score
  1140866  2017-03-24    0.04
  1140873  2017-03-24  0.1875
  1140874  2017-03-24   0.145
  1140894  2017-03-24  0.1125
  1140922  2017-03-24  0.0792
  1140952  2017-03-24   0.275
  1140956  2017-03-24  0.3425
  1140962  2017-03-24    0.11
  1140983  2017-03-24  0.1233
  1140992  2017-03-24   0.025
  1141001  2017-03-24  0.0431
  1141014  2017-03-24     0.1
  1141023  2017-03-24   0.075
  1141026  2017-03-24     0.8
  1141034  2017-03-24     0.1
  1141042  2017-03-24    0.04
  1141044  2017-03-24    0.06
  1141068  2017-03-24  0.0725
  1141079  2017-03-24  0.1087
  1141086  2017-03-24    0.06
  1141099  2017-03-24    0.15
  1141109  2017-03-24     0.8
  1141137  2017-03-24    0.18
  1141148  2017-03-24  0.0625
  1141155  2017-03-24  0.1875
  1141195  2017-03-24    0.15
  1141197  2017-03-24   0.085
  1141200  2017-03-24     0.2
  1141203  2017-03-24  0.1875
  1141210  2017-03-24    0.05
  ...             ...     ...
  1573896  2017-03-24   0.125
  1573901  2017-03-24   0.125
  1573903  2017-03-24   0.125
  1573910  2017-03-24   0.125
  1573926  2017-03-24   0.125
  1573927  2017-03-24   0.125
  1573928  2017-03-24   0.125
  1573929  2017-03-24   0.125
  1573943  2017-03-24   0.125
  1573953  2017-03-24   0.125
  1573956  2017-03-24   0.125
  1573960  2017-03-24   0.125
  1573962  2017-03-24   0.125
  1573985  2017-03-24   0.125
  1574060  2017-03-24   0.125
  1574193  2017-03-24   0.125
  1574210  2017-03-24   0.125
  1574225  2017-03-24   0.125
  1574333  2017-03-24   0.125
  1574336  2017-03-24   0.125
  1574362  2017-03-24   0.125
  1574452  2017-03-24   0.125
  1574503  2017-03-24   0.125
  1574554  2017-03-24   0.125
  1574568  2017-03-24   0.125
  1574582  2017-03-24   0.125
  1574660  2017-03-24   0.125
  1574726  2017-03-24   0.125
  1574737  2017-03-24   0.125
  1574759  2017-03-24   0.085

  [12702 rows x 2 columns]), (u'2017-03-25',                 day   score
  1309721  2017-03-25     0.3
  1309725  2017-03-25    0.16
  1309738  2017-03-25    0.08
  1309793  2017-03-25   0.535
  1309794  2017-03-25    0.05
  1309808  2017-03-25    0.25
  1309823  2017-03-25    0.05
  1309841  2017-03-25   0.355
  1309844  2017-03-25  0.0781
  1309867  2017-03-25   0.535
  1309870  2017-03-25   0.535
  1309890  2017-03-25    0.05
  1309904  2017-03-25    0.25
  1309905  2017-03-25    0.11
  1309942  2017-03-25    0.32
  1309979  2017-03-25  0.1875
  1309980  2017-03-25    0.25
  1309983  2017-03-25     0.7
  1310002  2017-03-25    0.35
  1310008  2017-03-25   0.075
  1310016  2017-03-25  0.0625
  1310028  2017-03-25    0.05
  1310061  2017-03-25     0.6
  1310088  2017-03-25   0.075
  1310106  2017-03-25   0.205
  1310143  2017-03-25  0.0533
  1310148  2017-03-25    0.12
  1310149  2017-03-25    0.22
  1310158  2017-03-25    0.35
  1310160  2017-03-25  0.0567
  ...             ...     ...
  1582611  2017-03-25   0.005
  1582640  2017-03-25    0.27
  1582775  2017-03-25    0.27
  1582916  2017-03-25   0.005
  1582932  2017-03-25   0.005
  1582996  2017-03-25   0.005
  1583431  2017-03-25  0.4375
  1583671  2017-03-25   0.175
  1583813  2017-03-25     0.5
  1583894  2017-03-25   0.005
  1583921  2017-03-25   0.005
  1584026  2017-03-25    0.22
  1584049  2017-03-25    0.22
  1584057  2017-03-25   0.005
  1584113  2017-03-25    0.22
  1584126  2017-03-25    0.22
  1584130  2017-03-25    0.22
  1584137  2017-03-25    0.22
  1584302  2017-03-25    0.25
  1584406  2017-03-25    0.25
  1584502  2017-03-25   0.135
  1584525  2017-03-25    0.22
  1584557  2017-03-25  0.1688
  1584612  2017-03-25  0.1688
  1584625  2017-03-25     0.1
  1585413  2017-03-25   0.275
  1585510  2017-03-25    0.16
  1585589  2017-03-25   0.125
  1585652  2017-03-25   0.275
  1585696  2017-03-25     0.1

  [14578 rows x 2 columns]), (u'2017-03-26',                 day   score
  1428363  2017-03-26  0.2125
  1428372  2017-03-26    0.09
  1428379  2017-03-26     0.3
  1428380  2017-03-26  0.1067
  1428386  2017-03-26    0.75
  1428403  2017-03-26     0.5
  1428412  2017-03-26     0.2
  1428414  2017-03-26  0.0833
  1428424  2017-03-26     0.3
  1428445  2017-03-26   0.055
  1428449  2017-03-26    0.22
  1428472  2017-03-26    0.25
  1428479  2017-03-26  0.0875
  1428482  2017-03-26    0.18
  1428493  2017-03-26  0.0225
  1428496  2017-03-26    0.05
  1428501  2017-03-26  0.0325
  1428502  2017-03-26     0.2
  1428507  2017-03-26    0.05
  1428551  2017-03-26    0.05
  1428552  2017-03-26  0.1313
  1428555  2017-03-26  0.1167
  1428557  2017-03-26     0.1
  1428561  2017-03-26  0.0625
  1428565  2017-03-26    0.04
  1428581  2017-03-26    0.22
  1428583  2017-03-26    0.22
  1428605  2017-03-26  0.0533
  1428608  2017-03-26    0.04
  1428610  2017-03-26    0.15
  ...             ...     ...
  1589001  2017-03-26     0.4
  1589146  2017-03-26  0.1875
  1589158  2017-03-26   0.135
  1589222  2017-03-26  0.1875
  1589226  2017-03-26  0.0938
  1589233  2017-03-26    0.22
  1589831  2017-03-26     0.1
  1589832  2017-03-26   0.275
  1589907  2017-03-26  0.2833
  1589952  2017-03-26   0.045
  1589954  2017-03-26   0.125
  1589993  2017-03-26   0.025
  1590034  2017-03-26     0.5
  1590107  2017-03-26  0.2833
  1590592  2017-03-26  0.2833
  1592237  2017-03-26    0.05
  1592287  2017-03-26   0.275
  1592402  2017-03-26   0.275
  1593483  2017-03-26    0.25
  1594576  2017-03-26     0.1
  1594581  2017-03-26   0.125
  1594982  2017-03-26    0.25
  1595265  2017-03-26   0.125
  1595285  2017-03-26   0.125
  1595365  2017-03-26   0.125
  1595397  2017-03-26   0.125
  1595403  2017-03-26   0.125
  1595628  2017-03-26     0.2
  1596143  2017-03-26  0.0267
  1598089  2017-03-26  0.2562

  [17382 rows x 2 columns]), (u'2017-03-27',                 day   score
  1598455  2017-03-27  0.0063
  1598469  2017-03-27    0.35
  1598471  2017-03-27    0.22
  1598473  2017-03-27     0.1
  1598485  2017-03-27     0.1
  1598488  2017-03-27     0.1
  1598509  2017-03-27   0.035
  1598534  2017-03-27    0.22
  1598542  2017-03-27    0.03
  1598556  2017-03-27    0.25
  1598567  2017-03-27    0.11
  1598570  2017-03-27   0.185
  1598579  2017-03-27     0.2
  1598582  2017-03-27    0.11
  1598589  2017-03-27    0.11
  1598594  2017-03-27    0.11
  1598610  2017-03-27    0.11
  1598619  2017-03-27    0.11
  1598628  2017-03-27     0.4
  1598631  2017-03-27    0.15
  1598636  2017-03-27    0.11
  1598641  2017-03-27    0.11
  1598643  2017-03-27    0.11
  1598648  2017-03-27  0.2875
  1598659  2017-03-27  0.0063
  1598665  2017-03-27     0.4
  1598676  2017-03-27    0.11
  1598678  2017-03-27  0.0733
  1598686  2017-03-27    0.11
  1598689  2017-03-27  0.0283
  ...             ...     ...
  2115733  2017-03-27     0.5
  2116431  2017-03-27     0.1
  2116467  2017-03-27    0.17
  2116706  2017-03-27     0.3
  2116747  2017-03-27  0.0967
  2116757  2017-03-27  0.0967
  2116763  2017-03-27    0.18
  2116764  2017-03-27  0.0967
  2116810  2017-03-27  0.0967
  2116914  2017-03-27  0.0967
  2116975  2017-03-27  0.0967
  2117010  2017-03-27  0.1333
  2117045  2017-03-27    0.25
  2117251  2017-03-27  0.0967
  2117373  2017-03-27     0.1
  2117393  2017-03-27   0.025
  2117795  2017-03-27    0.15
  2117904  2017-03-27    0.27
  2118240  2017-03-27    0.25
  2118346  2017-03-27    0.05
  2118457  2017-03-27     0.1
  2118493  2017-03-27     0.1
  2118639  2017-03-27    0.25
  2118714  2017-03-27     0.1
  2118721  2017-03-27     0.1
  2118738  2017-03-27     0.1
  2118865  2017-03-27     0.5
  2118866  2017-03-27    0.01
  2118870  2017-03-27  0.0967
  2119871  2017-03-27    0.03

  [16032 rows x 2 columns]), (u'2017-03-28',                 day   score
  1718139  2017-03-28  0.3331
  1718159  2017-03-28    0.22
  1718176  2017-03-28   0.275
  1718202  2017-03-28   0.075
  1718204  2017-03-28  0.0938
  1718209  2017-03-28  0.3433
  1718220  2017-03-28  0.1125
  1718241  2017-03-28    0.75
  1718254  2017-03-28     0.2
  1718256  2017-03-28  0.0333
  1718275  2017-03-28  0.3125
  1718277  2017-03-28    0.05
  1718283  2017-03-28     0.1
  1718284  2017-03-28     0.1
  1718302  2017-03-28   0.175
  1718307  2017-03-28     0.5
  1718315  2017-03-28  0.1812
  1718317  2017-03-28    0.25
  1718318  2017-03-28    0.41
  1718325  2017-03-28   0.005
  1718330  2017-03-28  0.0354
  1718351  2017-03-28     0.1
  1718360  2017-03-28   0.015
  1718361  2017-03-28     0.5
  1718381  2017-03-28   0.255
  1718382  2017-03-28    0.05
  1718389  2017-03-28    0.18
  1718391  2017-03-28    0.22
  1718416  2017-03-28  0.0175
  1718417  2017-03-28     0.5
  ...             ...     ...
  2124815  2017-03-28   0.075
  2124830  2017-03-28  0.1667
  2124838  2017-03-28   0.125

In [69]:
pos_Macron = df_day['day'].count()
pos_Macron

day
2017-03-18     7539
2017-03-19    19930
2017-03-20    37430
2017-03-21    44786
2017-03-22    20307
2017-03-23    21182
2017-03-24    12702
2017-03-25    14578
2017-03-26    17382
2017-03-27    16032
2017-03-28    18561
2017-03-29    27282
2017-03-30    15538
2017-03-31    16009
2017-04-01    28354
2017-04-02    22335
2017-04-03    18302
2017-04-04    31573
2017-04-05    19982
2017-04-06    37869
2017-04-07    20869
2017-04-08    14268
2017-04-09    17571
2017-04-10    19109
2017-04-11    17905
2017-04-12    20955
2017-04-13    16932
2017-04-14    22474
2017-04-15    23950
2017-04-16    20727
2017-04-17    34760
2017-04-18    19637
2017-04-19    20202
2017-04-20    35573
2017-04-21    30173
2017-04-22    17453
2017-04-23    59801
Name: day, dtype: int64

In [52]:
df_total=df.loc[df['score']>'0',['day','score','mention_Macron']]
df_totalDay=df_total.loc[df_total['day']<'2017-04-24',['day','score','mention_Macron']]
df_totalDay

                day   score  mention_Macron
0        2017-03-18     0.6               0
1        2017-03-18  0.2517               1
2        2017-03-18    0.21               0
3        2017-03-18  0.0217               1
4        2017-03-18  0.0633               0
5        2017-03-18    0.27               1
6        2017-03-18     0.0               0
7        2017-03-18  0.1171               0
8        2017-03-18     0.0               1
9        2017-03-18     0.0               0
11       2017-03-18   0.085               1
12       2017-03-18     0.0               1
13       2017-03-18     0.0               1
14       2017-03-18  0.2617               0
15       2017-03-18   0.175               0
16       2017-03-18     0.3               1
17       2017-03-18  0.0633               0
18       2017-03-18     0.0               0
19       2017-03-18     0.1               0
20       2017-03-18     0.7               0
21       2017-03-18    0.04               1
22       2017-03-18  0.1875               1
24       2017-03-18   0.075               0
25       2017-03-18    0.14               0
26       2017-03-18     0.2               0
27       2017-03-18    0.25               0
28       2017-03-18     0.0               0
29       2017-03-18  0.0567               0
32       2017-03-18     0.0               1
34       2017-03-18    0.21               1
...             ...     ...             ...
7820216  2017-04-09     0.0               0
7820217  2017-04-09     0.3               0
7820218  2017-04-09     0.0               0
7820219  2017-04-09     0.0               0
7820220  2017-04-09     0.0               0
7820221  2017-04-09     0.0               0
7820222  2017-04-09     0.0               0
7820223  2017-04-09     0.0               0
7820224  2017-04-09     0.0               0
7820225  2017-04-09     0.0               0
7820226  2017-04-09     0.0               0
7820227  2017-04-09     0.0               0
7820228  2017-04-09     0.0               0
7820229  2017-04-09     0.0               0
7820230  2017-04-09     0.0               0
7820231  2017-04-09     0.0               0
7820233  2017-04-09     0.0               0
7820234  2017-04-09     0.0               1
7820235  2017-04-09     0.0               0
7820236  2017-04-09     0.0               0
7820237  2017-04-09     0.0               0
7820239  2017-04-09     0.0               0
7820241  2017-04-09     0.0               0
7820242  2017-04-09     0.0               0
7820243  2017-04-09     0.0               0
7820244  2017-04-09     0.0               0
7820245  2017-04-09     0.0               0
7820246  2017-04-09     0.0               1
7820247  2017-04-09     0.0               0
7820250  2017-04-09     0.0               0

[5814681 rows x 3 columns]

In [55]:
df_totalPos = df_totalDay.groupby('day')
pos_Total = df_totalPos['day'].count()

In [56]:
per_posMacron = pos_Macron/pos_Total
per_posMacron

day
2017-03-18    0.150090
2017-03-19    0.187134
2017-03-20    0.145186
2017-03-21    0.179944
2017-03-22    0.156062
2017-03-23    0.140660
2017-03-24    0.085144
2017-03-25    0.138030
2017-03-26    0.152543
2017-03-27    0.149689
2017-03-28    0.170756
2017-03-29    0.211186
2017-03-30    0.148125
2017-03-31    0.171184
2017-04-01    0.244764
2017-04-02    0.208362
2017-04-03    0.153603
2017-04-04    0.130346
2017-04-05    0.124302
2017-04-06    0.216775
2017-04-07    0.176123
2017-04-08    0.139536
2017-04-09    0.122715
2017-04-10    0.130233
2017-04-11    0.122316
2017-04-12    0.143161
2017-04-13    0.127013
2017-04-14    0.149852
2017-04-15    0.156318
2017-04-16    0.158242
2017-04-17    0.204815
2017-04-18    0.108093
2017-04-19    0.104280
2017-04-20    0.138452
2017-04-21    0.121341
2017-04-22    0.104583
2017-04-23    0.132875
Name: day, dtype: float64

KeyError: 'the label [day] is not in the [index]'